# Generated by Django 5.1 on 2024-09-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_request', to='friends.friendrequest'),
        ),
    ]
