# Generated by Django 5.1 on 2024-09-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='friends.friendrequest'),
        ),
    ]
