# Generated by Django 5.1 on 2024-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request',
        ),
    ]
