# Generated by Django 5.1 on 2024-09-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_remove_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
